name: Docker CI (client/server/db)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker compose
      run: docker-compose -f docker/docker-compose.yml up -d --build