# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI (server)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: cd server && npm install
    - name: Linter check (server)
      run: cd server && npm run lint_check
    - name: Start db & server (testing preparation)
      run: docker-compose -f docker/docker-compose.yml up -d mongo &&\
           cd server && wget https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait -o /wait &&\
           chmod +x /wait && /wait && npm run start_testing_server
    - name: Run tests (server)
      run: cd server && npm run test
